# Generated by Django 6.0.5 on 2026-05-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Содержимое")),
                (
                    "image_product",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photo/",
                        verbose_name="Превью (изображение)",
                    ),
                ),
                (
                    "count_views",
                    models.IntegerField(verbose_name="Количество просмотров"),
                ),
                (
                    "is_publication",
                    models.BooleanField(verbose_name="Признак публикации"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
                "ordering": ["name"],
            },
        ),
    ]
