# Generated by Django 6.0.5 on 2026-05-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="image_product",
            new_name="image_blog",
        ),
    ]
