# Generated by Django 6.0.5 on 2026-05-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_image_product_blog_image_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="count_views",
            field=models.PositiveIntegerField(verbose_name="Количество просмотров"),
        ),
    ]
